views/profile.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, make_response
from flask_login import login_required, current_user
from lib.decorators import check_confirmed
from lib.utils import flash_errors
from forms import DepositForm, csrf
import datetime

userprofile = Blueprint('userprofile', __name__)

@userprofile.route('/profile')
@login_required
@check_confirmed
def profile():
    return render_template('profile/profile.html')

@userprofile.route('/dashboard')
@login_required
@check_confirmed
def dashboard():
	from sbb import db
	from models import PaymentSystems
	from models import Withdraws
	#investments = AccountInvestments.query.filter_by(accountId=current_user.account.id).limit(5)
	wths = Withdraws.query.filter(Withdraws.status==1, Withdraws.accountId==current_user.account.id).all()
	wamusd = float(0)
	wambtc = float(0)
	for w in wths:
		if w.wallet.paymentSystemId == 3:
			wamusd += float(w.amount)
		elif w.wallet.paymentSystemId == 4:
			wambtc += float(w.amount)
	investments = current_user.account.investments.filter_by(isActive=1).all()
	return render_template('profile/dashboard.html', 
							accId=current_user.account.id,
							accInvestments=investments,
							w_amount_usd = wamusd,
							w_amount_btc = wambtc)

@userprofile.route('/makedeposit')
@login_required
@check_confirmed
def makedeposit():
	from sbb import db
	from models import InvestmentPlan
	from models import PaymentSystems
	from sbb import application

	ps = PaymentSystems.query.filter(PaymentSystems.id > 2).all()
	ip = InvestmentPlan.query.filter_by(active=1).first()

	return render_template('profile/makedeposit.html', 
							ip=ip,
							paymentSystems=ps,
							minusd=application.config['MINUSDDEPOSIT'],
							maxusd=application.config['MAXUSDDEPOSIT'],
							minbtc=application.config['MINBTCDEPOSIT'],
							maxbtc=application.config['MAXBTCDEPOSIT']
							)


@userprofile.route('/confirm_deposit', methods=['POST'])
@login_required
@check_confirmed
def confirm_deposit():
	if request.method == 'POST':
		form = request.form
		psid = int(form.get('paymentSystemId', None))
		amount = float(form.get('amount', None))
		# ipid = form.get('invPlanId', None)
		# unit = form.get('unit', None)
		if psid and amount:
			from sbb import application
			if (psid == 1 or psid == 3) and amount < application.config['MINUSDDEPOSIT']:
				flash('Deposit value range violation')
				return redirect(url_for('userprofile.makedeposit'))
			elif (psid == 1 or psid == 3) and amount > application.config['MAXUSDDEPOSIT']:
				flash('Deposit value range violation')
				return redirect(url_for('userprofile.makedeposit'))
			if (psid == 2 or psid == 4) and amount < application.config['MINBTCDEPOSIT']:
				flash('Deposit value range violation')
				return redirect(url_for('userprofile.makedeposit'))
			elif (psid == 2 or psid == 4) and amount > application.config['MAXBTCDEPOSIT']:
				flash('Deposit value range violation')
				return redirect(url_for('userprofile.makedeposit'))
				
			from sbb import db
			from models import InvestmentPlan
			from models import PaymentSystems
			from models import Transaction
			from models import TransactionType
			from models import AccountInvestments

			# TBD taxes
			if psid == 1 and amount > current_user.account.balance:
				flash('You have not enough USD on your referral balance')
				return redirect(url_for('userprofile.makedeposit'))
			elif psid == 2 and amount > current_user.account.bitcoin:
				flash('You have not enough BTC on your referral balance')
				return redirect(url_for('userprofile.makedeposit'))

			trType = TransactionType.query.filter_by(id=3).first()
			ps = PaymentSystems.query.filter_by(id=psid).first()
			# active investmment plan
			ip = InvestmentPlan.query.filter_by(active=1).first()

			dep_act = Transaction(
									date=datetime.datetime.now(),
									amount=amount,
									status=0)
			dep_act.account = current_user.account
			dep_act.transactionType = trType
			dep_act.paymentSystem = ps
			dep_act.investmentPlan = ip
			dep_act.unit = ps.unit
			db.session.add(dep_act)
			db.session.commit()

			if psid == 1 or psid == 2:
				return render_template('profile/confirm_ref_deposit.html',
										invPlan=ip,
										paymentSystem=ps,
										amount=amount,
										depId=dep_act.id,
										unit=dep_act.unit,
dn=application.config['DOMAIN_NAME'])
			else:
				return render_template('profile/confirm_deposit.html',
										invPlan=ip,
										paymentSystem=ps,
										amount=amount,
										depId=dep_act.id,
										unit=dep_act.unit,
dn=application.config['DOMAIN_NAME'])
		else:
			flash('Invalid data supplied in deposit form {} - {}'.format(psid, amount))
			return redirect(url_for('userprofile.makedeposit'))

	else:
		return redirect(url_for('userprofile.makedeposit'))

@userprofile.route('/validate_deposit', methods=['POST'])
@csrf.exempt
def validate_deposit():
	from sbb import logger
	if request.method == 'POST':

		if request.headers.getlist("X-Forward-For"):
			req_ip = request.headers.getlist("X-Forward-For")[0]
		else:
			req_ip = request.remote_addr

		if str(req_ip) not in ['77.109.141.170', '91.205.41.208', '94.242.216.60', '78.41.203.75']:
			#logger.info('step 3')
			return make_response('error', 400)

		form = request.form

		pid = form.get('PAYMENT_ID', None)
		pyacc = form.get('PAYEE_ACCOUNT', None)
		pam = float(form.get('PAYMENT_AMOUNT', None))
		pu = form.get('PAYMENT_UNITS', None)
		pbn = form.get('PAYMENT_BATCH_NUM', None)
		pracc = form.get('PAYER_ACCOUNT', None)
		ts = form.get('TIMESTAMPGMT', None)
		v2 = form.get('V2_HASH', None)

		if pid and pyacc and pam and pu and pbn and pracc and ts and v2:
			from sbb import application
			import hashlib

			pmsecrethash = hashlib.md5(application.config['PMSECRET']).hexdigest().upper()
			
			ver = "{0}:{1}:{2}:{3}:{4}:{5}:{6}:{7}".format(pid, pyacc, str(pam), pu, pbn, pracc, pmsecrethash, ts)
			verhash = hashlib.md5(ver).hexdigest().upper()

			if v2 == verhash:
				from sbb import db
				from models import Transaction
				from models import AccountInvestments
				from models import Referral
				from models import ReferralBonuses

				trans = Transaction.query.filter_by(id=pid).first()
				if trans.status == 0:
					trans.status = 1
					db.session.add(trans)
					db.session.commit()
					return make_response('success', 200)
				else:
					return make_response('error', 401)
			else:
				return make_response('error', 402)
		else:
			return make_response('error', 403)


def __make_ref(ref, session, pam, ps):
	from models import ReferralBonuses
	from models import Referral
	if ref:
		parentAcc = ref.referralAccount
		refProg = parentAcc.referralProgram
		perc = int(refProg.level1)
		refBon = ReferralBonuses(current_user.account.id, pam, float(pam * perc  / 100), 1)
		refBon.earnedAccount = parentAcc
		refBon.payed = True
		session.add(refBon)

		# update balance of parrent account
		# PM or BC
		if ps.id in [1, 3]:
			parentAcc.balance += float(pam * perc  / 100)
		elif ps.id in [2, 4]:
			parentAcc.bitcoin += float(pam * perc  / 100)
		session.add(parentAcc)

		# grand parent account
		parentRef = Referral.query.filter_by(accountId=parentAcc.id).first()
		if parentRef:
			parentAcc = parentRef.referralAccount
			refProg = parentAcc.referralProgram
			perc = int(refProg.level2)
			refBon = ReferralBonuses(current_user.account.id, pam, float(pam * perc  / 100), 2)
			refBon.earnedAccount = parentAcc
			refBon.payed = True
			session.add(refBon)

			# update balance of parrent account
			if ps.id in [1, 3]:
				parentAcc.balance += float(pam * perc  / 100)
			elif ps.id in [2, 4]:
				parentAcc.bitcoin += float(pam * perc  / 100)
			session.add(parentAcc)

			# grand grand parent account
			grandRef = Referral.query.filter_by(accountId=parentAcc.id).first()
			if grandRef:
				parentAcc = grandRef.referralAccount
				refProg = parentAcc.referralProgram
				perc = int(refProg.level3)
				refBon = ReferralBonuses(current_user.account.id, pam, float(pam * perc  / 100), 3)
				refBon.earnedAccount = parentAcc
				refBon.payed = True
				session.add(refBon)

				# update balance of parrent account
				if ps.id in [1, 3]:
					parentAcc.balance += float(pam * perc  / 100)
				elif ps.id in [2, 4]:
					parentAcc.bitcoin += float(pam * perc  / 100)
				session.add(parentAcc)


@userprofile.route('/success_deposit', methods=['POST'])
@login_required
@check_confirmed
@csrf.exempt
def success_deposit():
	if request.method == 'POST':
		form = request.form

		pyacc = form.get('PAYEE_ACCOUNT', None)
		pam = float(form.get('PAYMENT_AMOUNT', None))
		pu = form.get('PAYMENT_UNITS', None)
		pbn = form.get('PAYMENT_BATCH_NUM', None)
		pracc = form.get('PAYER_ACCOUNT', None)
		pid = form.get('PAYMENT_ID', None)
		ts = form.get('TIMESTAMPGMT', None)
		v2 = form.get('V2_HASH', None)



		if pyacc and pam and pu and pbn and pracc and pid and ts and v2:
			
			#TEMP
			import hashlib
			from sbb import application
			from models import Transaction

			if application.config['PAYMENT_PROD']:
				trans = Transaction.query.filter_by(id=pid).first()
				if trans.status == 0:
					flash('Something goes wrong. Please try again')
					return redirect(url_for('userprofile.dashboard'))

			pmsecrethash = hashlib.md5(application.config['PMSECRET']).hexdigest().upper()
			ver = "{0}:{1}:{2}:{3}:{4}:{5}:{6}:{7}".format(pid, pyacc, str(pam), pu, pbn, pracc, pmsecrethash, ts)
			verhash = hashlib.md5(ver).hexdigest().upper()

			if v2 == verhash:
				from sbb import db
				from models import AccountInvestments
				from models import Referral
				from models import ReferralBonuses

				trans = Transaction.query.filter_by(id=pid).first()
				#if application.config['PAYMENT_PROD']

				if not application.config['PAYMENT_PROD'] and trans.status == 0:
					trans.status = 1
					db.session.add(trans)
				elif not application.config['PAYMENT_PROD'] and trans.status == 1:

templates/profile/activity.html
{% extends "profile/layout.html" %}
{% block body %}

<div class="row">
	<h2 style="color:#959595;  padding-left:10px">ACTIVITIES</h2>
	<hr style="width:100%">
</div>

<div class="row">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Date<span class="hidden-xs">Time</span></th>
				<th>Activity</th>
				<th>Status</th>
			</tr>
		</thead>
	{% for act in acts %}
		<tr>
			<td>{{ act.execDatetime | only_date}} <span class="hidden-xs">{{ act.execDatetime | only_time}}</span></td>
			{% if act.transactionTypeId == 3 or act.transactionTypeId == 5 %}
				<td>{{ act.transactionType.name }} | {{ act.amount }} {{act.unit}}</td>
				{% if act.status == False%}
				<td>Pending</td>
				{% else %}
					<td>Complet</td>
				{% endif %}
			{% else %}
			<td>{{ act.transactionType.name }}</td>
			<td>{{act.status}}</td>
			{% endif %}

		</tr>
	{% endfor %}
	</table>
</div>

{% endblock %}

templates/profile/confirm_deposit.html
{% extends "profile/layout.html" %}
{% block body %}

<div class="row">

<p>
	<center><h3>Please confirm you deposit</h3></center>
	<center>You are investing {{amount}}$ in "{{invPlan.description}}" investment plan.<center>
	<center>You have selected "{{paymentSystem.name}}" payment system. <center>
</p>

<form action="https://perfectmoney.is/api/step1.asp" method="POST">
<div class="block" style="border:1px">

	<!-- Perfect money data -->
	<input type="hidden" name="PAYEE_ACCOUNT" value="U16116460">
    <input type="hidden" name="PAYEE_NAME" value="SolarBit">
    <input type="hidden" name="PAYMENT_AMOUNT" value="{{amount}}">
    <input type="hidden" name="PAYMENT_UNITS" value="{{unit}}">
    <input type="hidden" name="STATUS_URL" value="{{dn}}/validate_deposit">
    <!-- <input type="hidden" name="STATUS_URL" value="mailto:araikc@gmail.com"> -->
    <input type="hidden" name="PAYMENT_URL" value="{{dn}}/success_deposit">
    <input type="hidden" name="PAYMENT_URL_METHOD" value="POST">
    <input type="hidden" name="NOPAYMENT_URL" value="{{dn}}/fail_deposit">
    <input type="hidden" name="NOPAYMENT_URL_METHOD" value="POST">
    <!-- <input type="hidden" name="BAGGAGE_FIELDS" value="ORDER_NUM CUST_NUM"> -->
    <!-- <input type="hidden" name="ORDER_NUM" value="9801121"> -->
    <!-- <input type="hidden" name="CUST_NUM" value="2067609"> -->
    <input type="hidden" name="SUGGESTED_MEMO" value="Invoice {{depId}}, {{g.user.username}}">
    <input type="hidden" name="PAYMENT_ID" value="{{depId}}">
    <br>
    <input type="submit" class="btn btn-success" name="PAYMENT_METHOD" value="Confirm">
	<a type="btn" class="btn" href="{{url_for('userprofile.makedeposit')}}">Cancel</a>


</div>
</form>

</div>

{% endblock %}

templates/profile/dashboard.html
{% extends "profile/layout.html" %}
{% block body %}

<div calss="row">
	<div class="col-xs-6 account-left"  style="border-right:1px solid #eee;">
		<div class="row">
			<h2 style="color:#959595;  padding-left:10px">ACCOUNT</h2>
			<hr style="width:95%">
		</div>
		<div style="min-width:200px">
			<div class="row">
				<div class="col-xs-6">
					<div  class="account_section">
						<p>
							All investments
						</p>
						<a href="makedeposit" class="btn btn-profile account-btn-middle"  style="margin-bottom:10px;" >New deposit</a>
					</div>
				</div>
				<div class="col-xs-6">
					<div class="account_numbers">
						<p>{{g_invusd}}<span class="fa fa-usd"></span></p>
						<p  class="bit">{{g_invbtc}}<span class="fa fa-btc"></span></p>
					</div>
				</div>
				<div>
					<hr style="width:95%; margin-top: 90px;">
				</div>
			</div>
			<div class="row">
				<div class="col-xs-6">
					<div  class="account_section">
						<p style="margin-bottom:10px">
							All withdraws
						</p>
					</div>
				</div>
				<div class="col-xs-6">
					<div class="account_numbers">
						<p>{{w_amount_usd}}<span class="fa fa-usd"></span></p>
						<p  class="bit">{{w_amount_btc}}<span class="fa fa-btc"></span></p>
					</div>
				</div>
				<div>
					<hr style="width:95%; margin-top: 90px;">
				</div>	
			</div>
			<div class="row">
				<div class="col-xs-6">
					<div  class="account_section">
						<p style="margin-bottom:10px">
							Referral bonuses
						</p>
						<a href="withdraw" class="btn btn-profile account-btn-middle"  style="margin-bottom:10px">Withdraw</a>
					</div>
				</div>
				<div class="col-xs-6">
					<div class="account_numbers">
						<p>{{g.user.account.balance}}<span class="fa fa-usd"></span></p>
						<p  class="bit">{{g.user.account.bitcoin}}<span class="fa fa-btc"></span></p>
					</div>
				</div>
				<div>
					<hr style="width:95%; margin-top: 90px;">
				</div>	
			</div>
			<div class="row">
				<div class="col-xs-6" style="margin-bottom:90px;">
					<div  class="account_section">
						<p style="margin-bottom:10px">
							Current profit
						</p>
						<a href="withdraw" class="btn btn-profile account-btn-middle"  style="margin-bottom:10px">Withdraw</a>
					</div>
				</div>
				<div class="col-xs-6">
					<div class="account_numbers">
						<p>{{g_ernusd}}<span class="fa fa-usd"></span></p>
						<p  class="bit">{{g_ernbtc}}<span class="fa fa-btc"></span></p>
					</div>
				</div>
<!-- 				<div>
					<hr style="width:95%; margin-top: 90px;">
				</div>	 -->
			</div>
		</div>
	</div>

	<div class="col-xs-6 account-right" >
		<div class="row">
			<h2 style="color:#959595;  padding-left:10px;">INVESTMENTS</h2>
			<!-- <hr style="width:95%"> -->
		</div>
		<!-- <div class="row">
			<div class="col-xs-6">
				<div  class="account_section">
					<a href="referrals" class="btn btn-info"  style="margin-bottom:10px">Referrals history</a>
				</div>
			</div>
			<div class="col-xs-6">
				<a href="deposits" class="btn btn-info"  style="margin-bottom:10px">Deposits history</a>
			</div>
			<div>
				<hr style="width:95%; margin-top: 90px;">
			</div>
		</div> -->
		{% if accInvestments %}
			{% for inv in accInvestments %}
			<div class="row">
				<hr style="width:95%; margin-top:5px">
				<div class="col-xs-8" style="border-right:1px solid #eee;">
					<div class="account_detail_section">
						<p>Invested amount</p>
					</div>
					<div class="account_detail_section">
						<p>Current balance</p>
					</div>
					<div class="account_detail_section">
						<p>Daily interest</p>
					</div>
					<div class="account_detail_section">
						<p>Active days</p>
					</div>
					<div class="account_detail_section">
						<p>Start date</p>
					</div>
				</div>
				<div class="col-xs-4">
					<div class="account_detail_section">
							{% if inv.paymentSystemId == 2 or inv.paymentSystemId == 4 %}
								<p class="bit">{{inv.initialInvestment}}<span class="fa fa-btc"></span></p>
							{% else %}
								<p class="usd">{{inv.initialInvestment}}<span class="fa fa-usd"></span></p>
							{% endif %}
					</div>

					<div class="account_detail_section">
							{% if inv.paymentSystemId == 2 or inv.paymentSystemId == 4 %}
								<p class="bit">{{inv.currentBalance}}<span class="fa fa-btc"></span></p>
							{% else %}
								<p class="usd">{{inv.currentBalance}}<span class="fa fa-usd"></span></p>
							{% endif %}
					</div>
					<div class="account_detail_section">
							<p>{{ inv.investmentPlan.percentage | clean_float }}%</p>
					</div>
					<div class="account_detail_section">
							<p>{{ inv.startDatetime | day_distance }} days</p>
					</div>
					<div class="account_detail_section">
							<p>{{ inv.startDatetime | only_date }}</p>
					</div>
				</div>
			</div>
			{% endfor %}
		{% else %}
			<div class="account_detail_section">
				<p>No any investments</p>
			</div>
		{% endif %}
	</div>
</div>
<!-- <div class="row">
	<h4>Active investments</h4>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Investment Plan</th>
				<th>Start</th>
				<th>End</th>
				<th>Amount invested</th>
				<th>Current ammount</th>
			</tr>
		</thead>
	{% for inv in accInvestments %}
		<tr>
			<td>{{ inv.investmentPlan.description }}</td>
			<td>{{ inv.startDatetime }}</td>
			<td>{{ inv.endDatetime }}</td>
			<td>{{ inv.initialInvestment }} {{inv.payment_unit}}</td>
			<td>{{ inv.currentBalance }} {{inv.payment_unit}}</td>
		</tr>
	{% endfor %}
	</table>
</div> -->

{% endblock %}

templates/profile/fail_deposit.html
{% extends "profile/layout.html" %}
{% block body %}

<div class="row">

<p>
	<center><h3>Your deposit not completed!</h3></center>
	<center>{{pam}}{{pu}} has not deposited to {{pyacc}}.<center>
</p>

<div class="row">
    <a href="{{url_for('userprofile.makedeposit')}}"> Make a new deposit</a> or check your  
    <a href="{{url_for('userprofile.deposits')}}"> Deposit history</a>
</div>

</div>

{% endblock %}

templates/profile/makedeposit.html
{% extends "profile/layout.html" %}
{% block body %}

<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>

<script type="text/javascript">

	$(document).ready(function($) {

		var maxusd = {{ maxusd }};
		var minusd = {{ minusd }};
		var maxbtc = {{ maxbtc }};
		var minbtc = {{ minbtc }};

		$('#validrange').text('[ ' + minusd + "$ - " + maxusd + '$ ]');

		$("input[name=paymentSystemId]").change(function() {
			var ps = document.getElementsByName('paymentSystemId');
			var sign = "$";
			for (var i = 0, length = ps.length; i < length; i++)
			{
				if (ps[i].checked && (ps[i].value == 4 || ps[i].value == 2)) 
				{
					$('#validrange').text('[ ' + minbtc + "Ƀ - " + maxbtc + 'Ƀ ]');
					sign = "Ƀ";
				}
				else if (ps[i].checked && (ps[i].value == 1 || ps[i].value == 3))
				{
					$('#validrange').text('[ ' + minusd + "$ - " + maxusd + '$ ]');
					sign = "$";
				}
			}

			if (sign == '$') {
				$('.cur-sign').removeClass('fa-btc');
				$('.cur-sign').removeClass('bit');
				$('.profit').removeClass('bit');
				$('.cur-sign').addClass('fa-usd');
			} else {
				$('.cur-sign').removeClass('fa-usd');
				$('.cur-sign').addClass('fa-btc');
				$('.cur-sign').addClass('bit');
				$('.profit').addClass('bit');
			} 

		});

    });

</script>

<style type="text/css">



</style>

<form action="{{ url_for('userprofile.confirm_deposit') }}" method=post class="form-horizontal" id="deposit"> 
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
<div class="block" style="border:1px">
		<div class="row">
			<h2 style="color:#959595;  padding-left:10px">DEPOSIT</h2>
			<hr style="width:100%">
		</div>
		<div class="row">
			<h2 style="color:#959595;  padding-left:10px; font-size:22px; padding-bottom:15px">Select source of investment</h2>
		</div>
	<div class="row">
			<div class="deposit-section">
				<h4 style="padding-left:15px; ">Referral bonusses</h4>

				<div style="margin-top:10px;" class="col-xs-6">
					<p>
						<input type="radio" name="paymentSystemId" id="paymentSystemIdusd" value="1" required {% if g.user.account.balance == 0 %} disabled {% endif %}>
						<label for="paymentSystemIdusd" class="radiotext" {% if g.user.account.balance == 0 %} style="opacity:0.5" {% endif %}>{{g.user.account.balance}}<span class="fa fa-usd"></span>
					</p>
				</div>
				<div style="margin-top:10px;" class="col-xs-6">
					<p>
						<input type="radio" name="paymentSystemId" id="paymentSystemIdbtc" value="2" required {% if g.user.account.bitcoin == 0 %} disabled {% endif %}>
						<label for="paymentSystemIdbtc" class="radiotext bit" {% if g.user.account.bitcoin == 0 %} style="opacity:0.5" {% endif %}>{{g.user.account.bitcoin}}<span class="fa fa-btc"></span>
					</p>
				</div>

			</div>
		<hr style="width:100%;">
	</div>
	<div class="row">
		<div class="deposit-section">
			<h4 style="padding-left:15px;">Payment Systems</h4>
			<div style="margin-top:10px">
			{% for ps in  paymentSystems %}
				<div class="col-xs-6">
					<p>
						<input type="radio" name="paymentSystemId" id="paymentSystemId{{ps.id}}" value="{{ps.id}}" required {% if  ps.id == 3 %} checked {% endif %}>
						<label for="paymentSystemId{{ps.id}}" style="margin-bottom:5px">
						{% if  ps.id == 3 %}
							<img class="pm-img">
						{% else %}
							<img class="bc-img">
						{% endif %}
						</label>
					</p>
				</div>
			{% endfor %}
			<div class="col-xs-6">
				<p>
					<input type="radio" name="paymentSystemId" id="paymentSystemId5" value="5" required disabled>
					<label for="paymentSystemId5" style="margin-bottom:5px">
						<img class="py-img disabled-obj">
					</label>
				</p>
			</div>
			<div class="col-xs-6">
				<p>
					<input type="radio" name="paymentSystemId" id="paymentSystemId6" value="6" required disabled>
					<label for="paymentSystemId6" style="margin-bottom:5px">
						<img class="adv-img disabled-obj">
					</label>
				</p>
			</div>
			</div>
		</div>
	<hr style="width:95%;">
	</div>
	<div class="row">
			<div class="col-xs-12 col-md-6 deposit-amount" >
				<h2 style="color:#959595;  padding-left:10px; font-size:22px;">Amount</h2>

				<div class="input-amount">
					<input name="amount" id="inv-amount" type="text" required style="width: 150px; font-weight:600" value="10">
				</div>
				<div class="row">
					<span class="profit-estimate" id="validrange" style="font-size: 14px; margin-left:20px"></span>
				</div>
				<div class="profits">
						<div class="profit-estimate" style="font-weight:600; font-size:16px">
							 Profit after
						</div>
					<div class="col-xs-6">
						<div class="profit-estimate">
							 Day
						</div>
						<div class="profit-estimate">
							 Month
						</div>
						<div class="profit-estimate">
							 Year
						</div>
					</div>
					<div class="col-xs-6">
						<div class="profit-estimate">
							<span class="fa fa-usd cur-sign"></span><span id="prof-value1" class="profit">0.3</span>
						</div>
						<div class="profit-estimate">
							<span class="fa fa-usd cur-sign"></span><span id="prof-value2" class="profit">9</span>
						</div>
						<div class="profit-estimate">
							<span class="fa fa-usd cur-sign"></span><span id="prof-value3" class="profit">109.5</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-md-6 current-plan" >
				<h2 style="color:#959595;  padding-left:10px; font-size:22px;">Current investment plan</h2>
				<h5 style="color:#959595;  padding-left:10px; font-size:14px; float:left">Percent</h5>
				<h5 style="color:#63cc88;  padding-left:10px; font-size:14px; text-align:right">{{ip.percentage|clean_float}}%</h5>
				<hr style="width:95%;  margin-top:-30px">  
				<h5 style="color:#959595;  padding-left:10px; font-size:14px; float:left">Withdraw</h5>
				<h5 style="color:#63cc88;  padding-left:10px; font-size:14px; text-align:right">Manual</h5>
				<hr style="width:95%;  margin-top:-30px">  	
				<h5 style="color:#959595;  padding-left:10px; font-size:14px; float:left">Withdraw period</h5>
				<h5 style="color:#63cc88;  padding-left:10px; font-size:14px; text-align:right">24h</h5>
				<hr style="width:95%;  margin-top:-30px">  	
				<h5 style="color:#959595;  padding-left:10px; font-size:14px; float:left">Deposit duration</h5>
				<h5 style="color:#63cc88;  padding-left:10px; font-size:14px; text-align:right">Unlimit</h5>
				<hr style="width:95%;  margin-top:-30px">
				<h5 style="color:#959595;  padding-left:10px; font-size:14px; float:left">Return deposit body</h5>
				<h5 style="color:#63cc88;  padding-left:10px; font-size:14px; text-align:right">No</h5>
			</div>
			<hr style="width:95%;" class="profits">
	</div>

	<div class="row">
		<div class="col-xs-12">
			<button type="submit" class="center-block btn btn-profile btn-large account-btn-middle" style="margin-bottom:90px; margin-top:10px">Invest</button>
		</div>
	</div>
</div>
</form>

{% endblock %}

templates/profile/profile.html
{% extends "profile/layout.html" %}
{% block body %}
<div id="main" class="container">
    <h1>Profile page of {{current_user.username}}</h1>
  
</div>
{% endblock %}