views/home.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session, g
from flask_login import login_user, logout_user, login_required, current_user
from forms import LoginForm, RegistrationForm, RequestResetPassordForm, ResetPassordForm
from datetime import datetime
from lib.token2 import generate_confirmation_token, confirm_token
from lib.decorators import check_confirmed, logout_required
from lib.utils import flash_errors
from datetime import datetime

home = Blueprint('home', __name__)

@home.route('/')
def index():
	# if current_user.is_authenticated:
	# 	return redirect(url_for('userprofile.dashboard'))
	# else:
	from models import PageData

	members = PageData.query.filter_by(name='members').first()
	invested = PageData.query.filter_by(name='invested').first()
	withdraw = PageData.query.filter_by(name='withdraw').first()

	ref = request.args.get('ref')
	if ref != None:
		session['referral'] = ref
	return render_template('home/index.html', members=members.value, invested=invested.value, withdraw=withdraw.value)

@home.route('/service')
def service():
		return render_template('home/service.html')

@home.route('/terms')
def terms():
		return render_template('home/terms.html')

@home.route('/privacy')
def privacy():
		return render_template('home/privacy.html')

@home.route('/antispam')
def antispam():
		return render_template('home/antispam.html')

@home.route('/about')
def about():
		return render_template('home/about.html')


@home.route('/faq')
def faq():
		return render_template('home/faq.html')


@home.route('/contact', methods=['GET','POST'])
def contact():
	from random import randint

	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/contact.html', a=session['a'], b=session['b'])
	else:
		form = request.form
		captcha = form.get('captcha', '')
		if captcha != '' and int(captcha) == session['a'] + session['b']:

			name = form.get('name', None)
			email = form.get('email', None)
			message = form.get('message', None)

			if name and email and message:
				from sbb import application
				#send email to user
				from lib.email2 import send_email
				html = render_template('home/contact_email.html', name=name, email=email, message=message)
				subject = "Contact email: {}".format(name)
				send_email("admin@solarbit.biz", subject, html, application.config)
			else:
				flash("Please fill all fields.")
		else:
			flash("Wrong captcha")
		flash("You have successfully sent email.")
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/contact.html', a=session['a'], b=session['b'])

@home.route('/register', methods=['GET','POST'])
@logout_required
def register():
	from random import randint

	from sbb import application, db
	from lib.email2 import send_email
	from models import User, ReferralProgram, Account, Referral

	referral = None
	if 'referral' in session:
		referral = session['referral']

	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		referral = None
		if 'referral' in session:
			referral = session['referral']
		return render_template('home/register.html', referral=referral, a=session['a'], b=session['b'])
	form = RegistrationForm(request.form)
	if form.validate_on_submit():
		captcha = form.captcha.data.strip()
		if captcha != '' and int(captcha) == session['a'] + session['b']:
			cur = User.query.filter_by(username=form.username.data).first()
			ecur = User.query.filter_by(email=form.email.data).first()

			if cur is None and ecur is None:

				# refereal program 521
				rp = ReferralProgram.query.filter_by(id=1).first()

				# Account User
				account = Account(0, 0)
				account.referralProgram = rp
				db.session.add(account)
				#db.session.commit()

				user = User(username=form.username.data, password=form.password.data, email=form.email.data)
				user.account = account
				if form.fb.data != '':
					user.fb = form.fb.data
				if form.skype.data != '':
					user.skype = form.skype.data
				user.pin = form.pin_number.data
				db.session.add(user)
				#db.session.commit()

				# referral account
				refUsername = form.refemail.data.strip()
				if refUsername != '':
					refUser = User.query.filter_by(username=refUsername).first()
					if refUser:
						referral = Referral(accountId=account.id)
						referral.referralAccount = refUser.account
						db.session.add(referral)
					else:
						flash("Wrong referral. Referral data skiped.")

				db.session.commit()

				token = generate_confirmation_token(user.email, application.config)
				confirm_url = url_for('home.confirm_email', token=token, _external=True)
				html = render_template('home/activate_email.html', confirm_url=confirm_url)
				subject = "Please confirm your email"
				send_email(user.email, subject, html, application.config)

				login_user(user)
				flash('A confirmation email has been sent via email.', 'success')
				return redirect(url_for('home.unconfirmed'))
			else:
				flash('User with specified data already exists in a system', 'warning')
		else:
			flash("Wrong captcha")
	else:
		flash_errors(form)
	session['a'] = randint(1, 10)
	session['b'] = randint(1, 10)
	return render_template('home/register.html', referral=referral, a=session['a'], b=session['b'])
 

@home.route('/login',methods=['GET','POST'])
@logout_required
def login():
	from random import randint
	from sbb import db
	from models import User
	from models import Transaction
	from models import TransactionType
	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/login.html', a=session['a'], b=session['b'])
	form = LoginForm(request.form)
	if form.validate_on_submit():
		captcha = form.captcha.data.strip()
		if captcha != '' and int(captcha) == session['a'] + session['b']:
			email = form.email.data
			password = form.password.data
			remember_me = False
			if 'remember_me' in request.form:
			    remember_me = True
			user = User.query.filter_by(email=email).first()
			tr = TransactionType.query.filter_by(id=1).first()
			if user is None or not user.check_password(password):
				flash('Username or Password is invalid' , 'error')
				if user:
					login_act = Transaction(
									date=datetime.now(),
									amount=None,
									status=0)
					login_act.account = user.account
					login_act.transactionType = tr
					db.session.add(login_act)
					db.session.commit()
				return redirect(url_for('home.login'))
			login_user(user, remember = remember_me)
			flash('Logged in successfully')
			login_act = Transaction(
									date=datetime.now(),
									amount=None,
									status=1)
			login_act.account = current_user.account
			login_act.transactionType = tr
			db.session.add(login_act)
			db.session.commit()
			return redirect(request.args.get('next') or url_for('userprofile.dashboard', _external=True, _scheme='https'))
		else:
			flash("Wrong captcha")
	flash_errors(form)
	session['a'] = randint(1, 10)
	session['b'] = randint(1, 10)
	return render_template('home/login.html', a=session['a'], b=session['b'])

@home.route('/view_reset_pass')
def view_reset_pass():
	return render_template('home/view_reset_pass.html')

@home.route('/confirm/<token>')
def confirm_email(token):
	from sbb import application, db
	from models import User
	email = None
	try:
		email = confirm_token(token=token, config=application.config)
	except Exception as e:
	    flash('The confirmation link is invalid or has expired.', 'danger')
	    return redirect(url_for('home.register'))
	user = User.query.filter_by(email=email).first_or_404()
	if user.confirmed:
	    flash('Account already confirmed. Please login.', 'success')
	else:
	    user.confirmed = True
	    user.confirmed_on = datetime.now()
	    db.session.add(user)
	    db.session.commit()
	    flash('You have confirmed your account. Thanks!', 'success')
	return redirect(url_for('home.login'))

@home.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
	from sbb import application
	email = None
	try:
	    email = confirm_token(token=token, config=application.config)
	except:
	    flash('The reset password link is invalid or has expired.', 'danger')
	    return redirect('login')
	return render_template('home/reset_password.html', email=email)

@home.route('/send_reset_pass', methods=['GET', 'POST'])
def send_reset_pass():
	from lib.email2 import send_email
	from models import User
	from sbb import application
	form = RequestResetPassordForm(request.form)
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user:
			token = generate_confirmation_token(form.email.data, application.config)
			reset_url = url_for('home.reset_password', token=token, _external=True)
			html = render_template('home/reset_password_email.html', reset_url=reset_url)
			subject = "Reset password request"
			send_email(form.email.data, subject, html, application.config)
			flash('We have sent you a link for resseting password.', 'success')
		else:
			flash('No user found with specified email.', 'warning')
			return redirect('view_reset_pass')
	else:
		flash_errors(form)
	return redirect('login')

@home.route('/save_reset_pass', methods=['POST'])
def save_reset_pass():
	from lib.email2 import send_email
	from models import User
	from models import Transaction
	from models import TransactionType
	from sbb import application, db
	form = ResetPassordForm(request.form)
	if form.validate_on_submit():
		user = User.query.filter_by(email=request.form['email']).first()
		if user:
			user.password = User.hash_password(form.password.data)
			db.session.add(user)
			tr = Transaction(datetime.now(), None, 1)
			tr.transactionTypeId = TransactionType.query.filter_by(id=6).first().id
			db.session.add(tr)
			db.session.commit()
			html = 'Thank you! You have successfully reset your password.'
			subject = "Reset password"

templates/home/_form_helper.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

templates/home/activate_email.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

templates/home/antispam.html
{% extends "layout.html" %}
{% block main %}

<section class="breadcrumb-section contact-bg section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <h1>ANTI SPAM POLICY</h1>
            </div>
        </div>
    </div>
</section>
 

 <div class="container">
     <div style="margin-top:30px; margin-bottom:50px">
        <h4>Email and Prohibited Content</h4>
        <p>Your use of Solarbit Limited company website https://Solarbit.biz/ is subject to this policy. If you are found to be in violation of our policies at any time, as determined by Solarbit Limited company in its sole discretion, we may warn you, or suspend or terminate your account. Please note that, in accordance with the Solarbit Limited company Terms of Use, we may change this policy at any time. It is your responsibility to keep up-to-date with and comply with this policy.</p>
        <br>
        <h4>Email Requirements</h4>
        <p>Solarbit Limited company has a zero-tolerance SPAM/UCE (unsolicited commercial e-mail) policy. This means that all email recipients must have opted in to, or otherwise validly consented to, receiving communications from you, the sender.</p>
        <p>You are responsible for ensuring that the email messages you send in connection with your surveys do not generate a number of spam complaints. If Solarbit Limited company determines that your level of spam complaints or bounce rate is higher than industry standards, Solarbit Limited, at its sole discretion, has the right to suspend or terminate your account. If you receive low response rates, high abuse rates or high bounce rates, we may request additional information regarding your mailing lists to investigate and attempt to resolve the problem.</p>
        <p>You are responsible for posting false votes or disinformation on public forums or any rating sites without contacting us at first.</p>
        <br>

        <h4>Any breach of this agreement as a whole or individual items can lead to permanent account suspension.</h4>

  </div>
</div>


{% endblock %}

templates/home/contact.html
{% extends "layout.html" %}
{% block main %}

     <!--header section start-->
      <section class="breadcrumb-section contact-bg section-padding">
      <div class="container">
          <div class="row">
              <div class="col-md-6 col-md-offset-3 text-center">
                  <h1>contact us</h1>
                 <!--   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p> -->
              </div>
          </div>
      </div>
      </section><!--Header section end-->

      <section class="get-in-touch section-padding text-center">
          <div class="container">
              <div class="row text-center">
                  <div class="col-md-4 wow pulse ">
                      <div class="single-shape-box">
                          <div class="get-in-tuch-icon">
                              <i class="fa fa-facebook"></i>
                          </div>
                          <div class="get-in-touch-text">
                              <h4>Follow us</h4>
                              <p><a href="http://facebook.com/solarbit" target="_blank">SolarBit</a></p>
                          </div>
                      </div>
                  </div>
                  <div class="col-md-4 wow pulse">
                      <div class="single-shape-box color-onvestor">
                          <div class="get-in-tuch-icon">
                              <i class="fa fa-location-arrow"></i>
                          </div>
                          <div class="get-in-touch-text">
                              <h4>Address </h4>
                              <p>Road 10,Sector 10,Uttara
                               <br /> Dhaka-1230,</p>
                          </div>
                      </div>
                  </div>
                  <div class="col-md-4 wow pulse" >
                      <div class="single-shape-box">
                          <div class="get-in-tuch-icon">
                              <i class="fa fa-envelope"></i>
                          </div>
                          <div class="get-in-touch-text">
                              <h4>Email</h4>
                              <p>support@solarbit.biz</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section>
      <!--get in touch section end-->

      <!--Map section start-->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29186.920133680236!2d90.36073541583481!3d23.876671847930258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c5d05e7074dd%3A0xd1c58803049f00c7!2sUttara%2C+Dhaka!5e0!3m2!1sen!2sbd!4v1505144892378"   allowfullscreen></iframe>
    </div><!--Map section end-->
      <!--Contact Form Start-->
      <section class="contact-section wow fadeInUp ">
          <div class="container">
              <div class="row">
                  <div class="col-md-12 text-center">
                     <div class="contact-form">
                      <div class="row">
                          <div class="col-md-8 col-md-offset-2">
                                  <h2 class="title">Send Your Masseage</h2>
                                  <form action="{{url_for('home.contact')}}" method="post">
                                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                      <input type="text" class="name" name="name" placeholder="Name">
                                      <input type="email" class="email" name="email" placeholder="Email">
                                      <textarea name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                                      <div class="row">
                                          <div class="col-md-3 col-sm-6">
                                              <p class="captcha-code">{{a}}+{{b}}=</p>
                                          </div>
                                          <div class="col-md-3 col-sm-6">
                                              <input type="number" min="0" max="20" class="captcha" name="captcha" placeholder="Answer">
                                          </div>
                                          <div class="col-md-6 col-sm-12">
                                              <input type="submit" value="Send Message Now!">
                                          </div>
                                      </div>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section><!--Contact Form end-->
      <!--get in touch section start-->


{% endblock %}

templates/home/privacy.html
{% extends "layout.html" %}
{% block main %}

<section class="breadcrumb-section contact-bg section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <h1>Privacy</h1>
            </div>
        </div>
    </div>
</section>
 

 <div class="container">
     <div style="margin-top:30px; margin-bottom:50px">
        <h3 style="margin-bottom: 35px;">PRIVACY</h3>
        <p>This policy describes how Solarbit Limited (collectively, “Solarbit Limited”, “we”, “us” or “our”) collects, uses, and shares the information we obtain from you online.</p>
        <br>
        <h4>What Our Privacy Policy Covers</h4>
        <p>This privacy policy discusses the “personal information” that Solarbit Limited obtains from you on <a href="/">Solarbit.biz</a>. When we use the term “personal information” we are referring to information that is connected to your name. This may include things like your e-mail address, e-currency account number, birthday (if available), telephone number (if available), or another profile information you provide.</p>
        <p>This privacy policy does not cover information that you submit on other websites, even if we communicate with you on those sites. For example, if you post something on instagram.com, facebook.com, twitter.com, telegram.org, slack.com, bitcointalk.org, youtube.com, that information is governed by the privacy policies on those websites, and is not governed by this policy.</p>
        <p>Note that we do not intentionally collect any personal information from people under the age of 18. If you are under the age of 18, you can look at our websites, but you should not make a purchase, register, or submit personal information to us.</p>
        <br>
        <h4>How We Use Your Personal Information</h4>
        <p>Solarbit Limited company primarily uses the personal information that it collects to provide you with news, information, and services of our company. We may also use your information to contact you for account and promotional purposes. We may also use your personal information for other legitimate business purposes, including to detect and prevent fraud, to collect amounts owing to us and to maintain business records.</p>
        <p>Solarbit Limited company may share de-identified information (i.e., information that is not directly connected to your name) in the following circumstance:</p>
        <p>Aggregate information. We may share de-identified aggregate information about our customers with advertisers and marketing partners.</p>
        <br>

        <h4>How We Protect Your Information</h4>
        <p>We realize that our customers trust us to protect their personal information. We take that task seriously and maintain physical, electronic and procedural safeguards to help protect your personal information.</p>
        <br>
        <h4>Communicating With Us</h4>
        <p>If you have any questions about our privacy or security practices, or of you would like to request access to or correction of your personal information, you can contact Solarbit Limited company by mail, telephone, or e-mail: support@solarbit.biz</p>
        <p>Your right to access or correct your personal information is subject to applicable legal restrictions. We may take reasonable steps to verify your identity before granting access or making corrections.</p>
        <p>If we need, or are required, to contact you concerning any event that involves your personal information we may do so by e-mail, telephone, or mail.</p>
        <br>
        <h4>Changes To This Policy</h4>
        <p>We may revise this policy from time to time. You should review our privacy policy periodically so that you keep up-to-date on our most current practices. We will note the effective date of the latest version at the end of each policy.</p>

  </div>
</div>


{% endblock %}

templates/home/profile.html
{% extends "layout.html" %}
{% block main %}
<div id="main" class="container">
    <h1>Profile page of {{current_user.username| make_caps}}</h1>
  
</div>
{% endblock %}

templates/home/register.html
{% extends "layout.html" %}
{% block main %}
    <!--header section start-->
    <section class="breadcrumb-section contact-bg section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <h1>Register</h1>
                </div>
            </div>
        </div>
    </section><!--Header section end-->


<!--login section start-->
<div class="login-section section-padding login-bg">
    <div class="container">
        <div class="row">
             <div class="col-md-6 col-md-offset-3">
      <div class="main-login main-center">
        <a href="index.html"><img src="static/img/logo.png" alt="Logo Image Will Be Here"></a>
          <form action="{{ url_for('home.register') }}" method=post class="form-horizontal">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

            <div class="form-group">
              <label for="name" class="cols-sm-2 control-label">Username</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                  <input type="text" class="form-control" name="username" id="username"  
                    placeholder="Enter your Name" value="{{ request.form.username }}" required/>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="email" class="cols-sm-2 control-label">Your Email</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                  <input type="text" class="form-control" name="email" id="email" 
                   placeholder="Enter your Email" value="{{ request.form.email }}"
                    required/>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="password" class="cols-sm-2 control-label">Password</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                  <input type="password" class="form-control" name="password" id="password" 
                   placeholder="Enter your Password" value="{{ request.form.password }}" required/>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                  <input type="password" class="form-control" name="password_repeat" id="password_repeat"  placeholder="Confirm your Password" value="{{ request.form.password_repeat }}" required/>
                </div>
              </div>
            </div>


            <div class="form-group">
              <label for="confirm" class="cols-sm-2 control-label">PIN number</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-user-secret fa-lg" aria-hidden="true"></i></span>
                  <input type="number" min="0" max="9999"  class="form-control" name="pin_number" id="pin_number"  placeholder="Pin number (4 digits)" value="{{request.form.pin_number}}" />
                </div>
                  <span style="font-size:12px">Keep PIN in safe place! Will be used during withdraw</span>
              </div>
            </div>

            <div class="form-group">
              <label for="confirm" class="cols-sm-2 control-label">Referral</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope fa-lg" aria-hidden="true"></i></span>
                  <input type="text" class="form-control" name="refemail" id="refemail"  placeholder="Referral" value="{% if referral %} {{referral}} {% endif  %}"/>
                </div>
              </div>
            </div>

            <div class="form-group">
                  <div style="float:left">
                      <a id="social_button" style="cursor: pointer; font-weight:800">Social</a>
                  </div> 
                  <div class="reg-accept">
                    <input type="checkbox" name="accept" id="accept" novalidate/>
                    <label for="accept" style="font-weight:300"><i class="fa fa-check" aria-hidden="true"></i>I accept</label>
                    <a href="{{url_for('home.terms')}}" target="_blank">Terms and Conditions</a>
                  </div>
            </div>

            <div class="social_register_hidden" id="social_register">
              <div class="form-group">
                <label for="confirm" class="cols-sm-2 control-label">Facebook</label>
                <div class="cols-sm-10">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-facebook-official fa-lg" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="fb" id="fb"  placeholder="Facebook" />
                  </div>
                </div>
              </div>

              <div class="form-group">
                <label for="confirm" class="cols-sm-2 control-label">Skype name</label>
                <div class="cols-sm-10">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-skype fa-lg" aria-hidden="true"></i></span>
                    <input type="text" class="form-control" name="skype" id="skype"  placeholder="Skype name"/>
                  </div>
                </div>
              </div>
            </div>

            <div class="form-group">
                  <div class="col-md-12 col-sm-12 col-xs-12 captcha-new">
                    <label for="captcha">{{a}}+{{b}}=</label>
                    <input  type="number" min="0" max="20" name="captcha" placeholder="">
                  </div>
                  <button type="submit" class="submit-btn btn btn-lg btn-block login-button">Register</button>
            </div>

          </form>
        </div>   
       </div>
        </div>
    </div>
</div>


{% endblock %}

templates/home/reset_password.html
{% extends "layout.html" %}
{% block main %}

<!--header section start-->
<section class="breadcrumb-section contact-bg section-padding">
  <div class="container">
      <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
              <h1>Reset</h1>
          </div>
      </div>
  </div>
</section><!--Header section end-->

<div class="login-section section-padding login-bg">
  <div class="container">
    <div class="row">
       <div class="col-md-6 col-md-offset-3">
         <div class="main-login main-center">
        <a href="index.html"><img src="assets/img/logo.png" alt="Logo Image Will Be Here"></a>
          <form action="{{ url_for('home.save_reset_pass') }}" method=post class="form-horizontal">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input type="hidden" name="email" value="{{ email }}"/>

            <div class="form-group">
              <label for="email" class="cols-sm-2 control-label">Password</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                  <input type="password" class="form-control" name="password" id="password"  placeholder="New Password" required value="{{ request.form.password }}"/>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="email" class="cols-sm-2 control-label">Repeat Password</label>
              <div class="cols-sm-10">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                  <input type="password" class="form-control" name="password_repeat" id="password_repeat"  placeholder="Repeat Password" required value="{{ request.form.password_repeat }}"/>
                </div>
              </div>
            </div>

            <div class="form-group ">
              <button type="submit" class="submit-btn btn btn-lg btn-block login-button">Reset</button>
            </div>

          </form>
        </div>
       </div>
    </div>
  </div>
</div>


{% endblock %}

templates/home/reset_password_email.html
<p>Please follow this link to reset your password:</p>
<p><a href="{{ reset_url }}">{{ reset_url }}</a></p>
<br>
<p>Cheers!</p>

templates/home/withdraw_request_email.html
<p>
	<center><h3> Withdraw request </h3></center>
	<center>We have received withdraw request from #{{account.id}} account.<center>
	<center><h4>Wallet info</h4><center>
	<center>Payment system: {{accW.wallet.name}}<center>
	<center>Wallet number: {{accW.walletValue}}<center>
	<center><h4>User info</h4><center>
	<center>Amount requested: {{amount}}{{accW.wallet.unit}}<center>
	<center>User current balance: 
		{% if accW.wallet.unit == 'BTC' %}
			{{account.bitcoin}}BTC
		{% else %}
			{{account.balance}}{{accW.wallet.unit}}
		{% endif %}
	<center>
</p>