views/home.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session, g
from flask_login import login_user, logout_user, login_required, current_user
from forms import LoginForm, RegistrationForm, RequestResetPassordForm, ResetPassordForm
from datetime import datetime
from lib.token2 import generate_confirmation_token, confirm_token
from lib.decorators import check_confirmed, logout_required
from lib.utils import flash_errors
from datetime import datetime

home = Blueprint('home', __name__)

@home.route('/')
def index():
	# if current_user.is_authenticated:
	# 	return redirect(url_for('userprofile.dashboard'))
	# else:
	from models import PageData

	members = PageData.query.filter_by(name='members').first()
	invested = PageData.query.filter_by(name='invested').first()
	withdraw = PageData.query.filter_by(name='withdraw').first()

	ref = request.args.get('ref')
	if ref != None:
		session['referral'] = ref
	return render_template('home/index.html', members=members.value, invested=invested.value, withdraw=withdraw.value)

@home.route('/service')
def service():
		return render_template('home/service.html')

@home.route('/terms')
def terms():
		return render_template('home/terms.html')

@home.route('/privacy')
def privacy():
		return render_template('home/privacy.html')

@home.route('/antispam')
def antispam():
		return render_template('home/antispam.html')

@home.route('/about')
def about():
		return render_template('home/about.html')


@home.route('/faq')
def faq():
		return render_template('home/faq.html')


@home.route('/contact', methods=['GET','POST'])
def contact():
	from random import randint

	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/contact.html', a=session['a'], b=session['b'])
	else:
		form = request.form
		captcha = form.get('captcha', '')
		if captcha != '' and int(captcha) == session['a'] + session['b']:

			name = form.get('name', None)
			email = form.get('email', None)
			message = form.get('message', None)

			if name and email and message:
				from sbb import application
				#send email to user
				from lib.email2 import send_email
				html = render_template('home/contact_email.html', name=name, email=email, message=message)
				subject = "Contact email: {}".format(name)
				send_email("admin@solarbit.biz", subject, html, application.config)
			else:
				flash("Please fill all fields.")
		else:
			flash("Wrong captcha")
		flash("You have successfully sent email.")
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/contact.html', a=session['a'], b=session['b'])

@home.route('/register', methods=['GET','POST'])
@logout_required
def register():
	from random import randint

	from sbb import application, db
	from lib.email2 import send_email
	from models import User, ReferralProgram, Account, Referral

	referral = None
	if 'referral' in session:
		referral = session['referral']

	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		referral = None
		if 'referral' in session:
			referral = session['referral']
		return render_template('home/register.html', referral=referral, a=session['a'], b=session['b'])
	form = RegistrationForm(request.form)
	if form.validate_on_submit():
		captcha = form.captcha.data.strip()
		if captcha != '' and int(captcha) == session['a'] + session['b']:
			cur = User.query.filter_by(username=form.username.data).first()
			ecur = User.query.filter_by(email=form.email.data).first()

			if cur is None and ecur is None:

				# refereal program 521
				rp = ReferralProgram.query.filter_by(id=1).first()

				# Account User
				account = Account(0, 0)
				account.referralProgram = rp
				db.session.add(account)
				#db.session.commit()

				user = User(username=form.username.data, password=form.password.data, email=form.email.data)
				user.account = account
				if form.fb.data != '':
					user.fb = form.fb.data
				if form.skype.data != '':
					user.skype = form.skype.data
				user.pin = form.pin_number.data
				db.session.add(user)
				#db.session.commit()

				# referral account
				refUsername = form.refemail.data.strip()
				if refUsername != '':
					refUser = User.query.filter_by(username=refUsername).first()
					if refUser:
						referral = Referral(accountId=account.id)
						referral.referralAccount = refUser.account
						db.session.add(referral)
					else:
						flash("Wrong referral. Referral data skiped.")

				db.session.commit()

				token = generate_confirmation_token(user.email, application.config)
				confirm_url = url_for('home.confirm_email', token=token, _external=True)
				html = render_template('home/activate_email.html', confirm_url=confirm_url)
				subject = "Please confirm your email"
				send_email(user.email, subject, html, application.config)

				login_user(user)
				flash('A confirmation email has been sent via email.', 'success')
				return redirect(url_for('home.unconfirmed'))
			else:
				flash('User with specified data already exists in a system', 'warning')
		else:
			flash("Wrong captcha")
	else:
		flash_errors(form)
	session['a'] = randint(1, 10)
	session['b'] = randint(1, 10)
	return render_template('home/register.html', referral=referral, a=session['a'], b=session['b'])
 

@home.route('/login',methods=['GET','POST'])
@logout_required
def login():
	from random import randint
	from sbb import db
	from models import User
	from models import Transaction
	from models import TransactionType
	if request.method == 'GET':
		session['a'] = randint(1, 10)
		session['b'] = randint(1, 10)
		return render_template('home/login.html', a=session['a'], b=session['b'])
	form = LoginForm(request.form)
	if form.validate_on_submit():
		captcha = form.captcha.data.strip()
		if captcha != '' and int(captcha) == session['a'] + session['b']:
			email = form.email.data
			password = form.password.data
			remember_me = False
			if 'remember_me' in request.form:
			    remember_me = True
			user = User.query.filter_by(email=email).first()
			tr = TransactionType.query.filter_by(id=1).first()
			if user is None or not user.check_password(password):
				flash('Username or Password is invalid' , 'error')
				if user:
					login_act = Transaction(
									date=datetime.now(),
									amount=None,
									status=0)
					login_act.account = user.account
					login_act.transactionType = tr
					db.session.add(login_act)
					db.session.commit()
				return redirect(url_for('home.login'))
			login_user(user, remember = remember_me)
			flash('Logged in successfully')
			login_act = Transaction(
									date=datetime.now(),
									amount=None,
									status=1)
			login_act.account = current_user.account
			login_act.transactionType = tr
			db.session.add(login_act)
			db.session.commit()
			return redirect(request.args.get('next') or url_for('userprofile.dashboard', _external=True, _scheme='https'))
		else:
			flash("Wrong captcha")
	flash_errors(form)
	session['a'] = randint(1, 10)
	session['b'] = randint(1, 10)
	return render_template('home/login.html', a=session['a'], b=session['b'])

@home.route('/view_reset_pass')
def view_reset_pass():
	return render_template('home/view_reset_pass.html')

@home.route('/confirm/<token>')
def confirm_email(token):
	from sbb import application, db
	from models import User
	email = None
	try:
		email = confirm_token(token=token, config=application.config)
	except Exception as e:
	    flash('The confirmation link is invalid or has expired.', 'danger')
	    return redirect(url_for('home.register'))
	user = User.query.filter_by(email=email).first_or_404()
	if user.confirmed:
	    flash('Account already confirmed. Please login.', 'success')
	else:
	    user.confirmed = True
	    user.confirmed_on = datetime.now()
	    db.session.add(user)
	    db.session.commit()
	    flash('You have confirmed your account. Thanks!', 'success')
	return redirect(url_for('home.login'))

@home.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
	from sbb import application
	email = None
	try:
	    email = confirm_token(token=token, config=application.config)
	except:
	    flash('The reset password link is invalid or has expired.', 'danger')
	    return redirect('login')
	return render_template('home/reset_password.html', email=email)

@home.route('/send_reset_pass', methods=['GET', 'POST'])
def send_reset_pass():
	from lib.email2 import send_email
	from models import User
	from sbb import application
	form = RequestResetPassordForm(request.form)
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user:
			token = generate_confirmation_token(form.email.data, application.config)
			reset_url = url_for('home.reset_password', token=token, _external=True)
			html = render_template('home/reset_password_email.html', reset_url=reset_url)
			subject = "Reset password request"
			send_email(form.email.data, subject, html, application.config)
			flash('We have sent you a link for resseting password.', 'success')
		else:
			flash('No user found with specified email.', 'warning')
			return redirect('view_reset_pass')
	else:
		flash_errors(form)
	return redirect('login')

@home.route('/save_reset_pass', methods=['POST'])
def save_reset_pass():
	from lib.email2 import send_email
	from models import User
	from models import Transaction
	from models import TransactionType
	from sbb import application, db
	form = ResetPassordForm(request.form)
	if form.validate_on_submit():
		user = User.query.filter_by(email=request.form['email']).first()
		if user:
			user.password = User.hash_password(form.password.data)
			db.session.add(user)
			tr = Transaction(datetime.now(), None, 1)
			tr.transactionTypeId = TransactionType.query.filter_by(id=6).first().id
			db.session.add(tr)
			db.session.commit()
			html = 'Thank you! You have successfully reset your password.'
			subject = "Reset password"

templates/layout.html
{% from "macros.html" import nav_link with context %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SolarBit</title>

        <!--Favicon add-->
    	<link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/fevicon.png')}}">
        <!--bootstrap Css-->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
        <!--font-awesome Css-->
        <link href="{{ url_for('static', filename='css/font-awesome.min.css')}}" rel="stylesheet">
        <!--owl.carousel Css-->
        <link href="{{ url_for('static', filename='css/owl.carousel.css')}}" rel="stylesheet">
        <!--Slick Nav Css-->
        <link href="{{ url_for('static', filename='css/slicknav.min.css')}}" rel="stylesheet">
        <!--Animate Css-->
        <link href="{{ url_for('static', filename='css/animate.css')}}" rel="stylesheet">
        <!--Style Css-->
        <link href="{{ url_for('static', filename='css/style.css')}}" rel="stylesheet">

        <link href="{{ url_for('static', filename='css/home.css')}}" rel="stylesheet">
        <!--Responsive Css-->
        <link href="{{ url_for('static', filename='css/responsive.css')}}" rel="stylesheet">

        <link href="{{ url_for('static', filename='css/common.css')}}" rel="stylesheet">

    </head>

    <body>

    <div class="select-language small-lang" id="lang-select">
        <div class="language-href"><a href="javascript:void(0);"><i class="flag flag_en"></i>ENG</a></div>
        <div class="language-tab">
            <ul class="language-list">
                <li>
                    <a href="?language=en"><i class="flag flag_en"></i>ENG</a>
                </li>
                <li>
                    <a  class="disabled" href="?language=ru"><i class="flag flag_ru"></i>RUS</a>
                </li>
                <li>
                    <a class="disabled" href="?language=de"><i class="flag flag_de"></i>DEU</a>
                </li>
                <li>
                    <a class="disabled" href="?language=es"><i class="flag flag_ge"></i>ESP</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="Switcher">
        <i class="fa fa-calculator" id="Switch-button"></i>
        <h5 style="margin-bottom: 5px">Profit calculator</h5>
        <!-- <ul id="colors" data-dir="assets/css/themes/">
            <li class="theme-3"><span>y</span></li>
            <li class="theme-4"><span>y</span></li>
            <li class="theme-6"><span>p</span></li>
            <li class="theme-9"><span>p</span></li>
            <li class="theme-13"><span>p</span></li>
            <li class="theme-14"><span>p</span></li>
        </ul> -->
        <div class="calc-body">
          <div style="float:left" class="calc-input">
            <input type="text" id="calc-amount" placeholder="Deposit"/>
            <input type="text" id="calc-percent" placeholder="Percent" value="3%"/>
            <input type="text" id="calc-days" placeholder="Days"/>
          </div>
          <div style="float:left" class="calc-output">
            <span style="color:#049426; font-size:18px; font-weight:600">Profit</span>
            <br>
            <span id="calc-out" style="color:#63cc88; font-size:28px; font-weight:600">0</span>
          </div>
        </div>
    </div>

    <div class="SocialQA">
        <ul id="socials">
            <li><i class="fa fa-facebook"></i></li>
            <li><i class="fa fa-twitter"></i></li>
            <li><i class="fa fa-youtube-play"></i></li>
        </ul>
    </div>

    <!--Preloader start-->
    <div class="preloader">
        <div class="spinner">
          <div class="cube1"></div>
          <div class="cube2"></div>
        </div>
    </div>
    <!--Preloader end-->
<div class="site"><!--for boxed Layout start-->

    <!--Scroll to top start-->
    <div class="scroll-to-top">
        <a href=""><i class="fa fa-caret-up"></i></a>
    </div><!--Scroll to top end-->

    <!--mobile logo -->
    <div class="mobile-logo">
        <a href="{{url_for('home.index')}}"><img src="static/img/mobile-logo.png" alt="SolarBit"></a>
    </div>

	 <!--main menu start-->
    <nav class="main-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="logo">
                    <!-- <a href="index.html"><img src="assets/img/logo.png" alt="Logo Image Will Be Here"></a> -->
                    <a href="{{url_for('home.index')}}"><img src="{{ url_for('static', filename='img/logo.png') }}" alt="SolarBit"></a>
                    </div>
                    
                    <div class="select-language big-lang" id="lang-select">
                        <div class="language-href"><a href="javascript:void(0);"><i class="flag flag_en"></i>ENG</a></div>
                        <div class="language-tab">
                            <ul class="language-list">
                                <li>
                                    <a href="?language=en"><i class="flag flag_en"></i>ENG</a>
                                </li>
                                <li>
                                    <a  class="disabled" href="?language=ru"><i class="flag flag_ru"></i>RUS</a>
                                </li>
                                <li>
                                    <a class="disabled" href="?language=de"><i class="flag flag_de"></i>DEU</a>
                                </li>
                                <li>
                                    <a class="disabled" href="?language=es"><i class="flag flag_ge"></i>ESP</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 text-right">
                    
                    <nav>
                        <ul id="menu-bar">
                        {{ nav_link('home.index', "Home") }}
                        {{ nav_link('home.about', "About Us") }}
                        {{ nav_link('home.service', "Referral") }}
                        {{ nav_link('home.faq', "FAQ") }}
                        {{ nav_link('home.contact', "Contact") }}
                        {% if g.user.is_authenticated %}
                        <li><a href="{{url_for('userprofile.dashboard')}}" class="btn-border username-btn">{{g.user.username}}</a></li>
                        {% else %}
                        <li><a href="{{url_for('userprofile.dashboard')}}" class="btn-border">Account</a>
                          <ul class="sub-menu">
                          	{% if not g.user.is_authenticated %}
                                {{ nav_link('home.login', "Login") }}
                                {{ nav_link('home.register', "Register") }}
                            {% endif %}
                          </ul>
                        </li>
                        {% endif %}
                        {% if g.user.is_authenticated %}
                          {{ nav_link('home.logout', "Logout") }}
                        {% endif %}
                    </ul>
                    </nav>

                </div>
            </div>
        </div>
    </nav><!--main menu end-->


<!--     <div class="select-language main-area-lang" id="lang-select">
        <div class="language-href"><a href="javascript:void(0);"><i class="flag flag_en"></i>ENG</a></div>
        <div class="language-tab">
            <ul class="language-list">
                <li>
                    <a href="?language=en"><i class="flag flag_en"></i>ENG</a>
                </li>
                <li>
                    <a  class="disabled" href="?language=ru"><i class="flag flag_ru"></i>RUS</a>
                </li>
                <li>
                    <a class="disabled" href="?language=de"><i class="flag flag_de"></i>DEU</a>
                </li>
                <li>
                    <a class="disabled" href="?language=es"><i class="flag flag_ge"></i>ESP</a>
                </li>
            </ul>
        </div>
    </div> -->


    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info fade in alert-dismissable" id="flash-alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
          <strong>Info!</strong> {{message}}
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block main %}{% endblock %}

    <footer class="footer-section section-padding padding-bottom-0 text-center">
           <div class="row footer-top">
               <div class="col-md-4 col-md-offset-4">
                  <div class="footer-social-link">
                      <h3>Follow Us on</h3>
                      <div class="social-link">
                          <a href=""><i class="fa fa-facebook"></i></a>
                          <a href=""><i class="fa fa-twitter"></i></a>
                          <a href=""><i class="fa fa-youtube"></i></a>
                          <a href="" class="not-active"><i class="fa fa-instagram"></i></a>
                          <a href="" class="not-active"><i class="fa fa-pinterest"></i></a>
                      </div>
                  </div>
               </div>
           </div>
           <div class="row footer-bottom-expanded" style="background-color:#2c2b2a; padding-bottom: 10px;">
             <div class="col-xs-1 footer-delimeter ">
             </div>
             <div class="col-xs-3 footer-delimeter">
                <div style=" border-right:1px solid #7e7b79;">
                  <div class="footer-logo">
                      <a href="index.html"><img src="static/img/logo.png" alt="Footer Logo"></a>
                  </div>
                    <div style="text-align:left">
                      <p style="font-size:16px; font-weight:500; color:white; font-family:'Poppins', sans-serif; margin-bottom: 0px;">150 New Bond Street, Mayfair, London, <br> United Kingdom, W1S 2TU</p>
                  </div>
                  <div style="text-align:left">
                      <br>
                      <p style="font-size:16px; font-weight:500; color:white; font-family:'Poppins', sans-serif; margin-bottom: 0px;">© 2018 SolarBit</p>
                      <span style="color:#585653; font-size:14px">All rights reserved</span>
                  </div>
                </div>
             </div>
             <div class="col-xs-2 footer-delimeter ">
                <h3>COMPANY</h3>
                <a href="{{url_for('home.about')}}">About us</a>
                <a href="{{url_for('home.service')}}">Referral</a>
             </div>
             <div class="col-xs-2 footer-delimeter ">
              <h3>INFORMATION</h3>
                <a href="{{url_for('home.antispam')}}">AntiSpam Policy</a>
                <a href="{{url_for('home.faq')}}">FAQ</a>
                <a href="{{url_for('home.privacy')}}">Privacy</a>
                <a href="{{url_for('home.terms')}}">Terms &amp; Conditions</a>
             </div>
             <div class="col-xs-2 footer-delimeter ">
              <h3>CONTACTS</h3>
                <a href="{{url_for('home.contact')}}">Contact</a>
                <a> support@solarbit.biz</a>
                <div class="social-links-bottom" style="margin-top:10px">
                  <a href=""><i class="fa fa-facebook"></i></a>
                  <a href=""><i class="fa fa-twitter"></i></a>
                  <a href=""><i class="fa fa-youtube"></i></a>
                </div>
             </div>
           </div>
           <div class="footer-bottom">
               <p class="copyright-text">COPY RIGHTS &copy; 2018. ALL RIGHTS RESERVED </p>
           </div>
    </footer><!--footer section end-->

<!-- The Modal -->
<div id="imgModal" class="modal">
  <span class="imgDialogClose">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

</div><!--for boxed Layout end: site end--> 

<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
 <!--Owl carousel script load-->
<script src="{{ url_for('static', filename='js/owl.carousel.min.js')}}"></script>
<!--Bootstrap v3 script load here-->
<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
<!--Slick Nav Js File Load-->
<script src="{{ url_for('static', filename='js/jquery.slicknav.min.js')}}"></script>
<!--Wow Js File Load-->
<script src="{{ url_for('static', filename='js/wow.min.js')}}"></script>
 <!--Main js file load-->
<script src="{{ url_for('static', filename='js/main.js')}}"></script>
<script src="{{ url_for('static', filename='js/common.js')}}"></script>
<script src="{{ url_for('static', filename='js/home.js')}}"></script>
</body>
</html>

templates/macros.html
{# myapp/templates/macros.html #}

{% macro nav_link(endpoint, text) %}
{% if request.endpoint.endswith(endpoint) %}
<li class="active"><a href="{{ url_for(endpoint) }}">{{text}}</a></li>
{% else %}
<li><a href="{{ url_for(endpoint) }}">{{text}}</a></li>
{% endif %}
{% endmacro %}

{% macro active_link(routeName) %}
{% if request.endpoint.endswith(routeName) %}
class="active"
{% else %}
{% endif %}
{% endmacro %}